/**
 * Read-only project-governance primitives and commands.
 *
 * This module may inspect repository files, Git history, and linked worktrees,
 * but it must not create directories, acquire write locks, or modify state.
 */

import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

export const RESUME_DEFAULT_COMMIT_LIMIT = 3;
export const RESUME_MAX_COMMIT_LIMIT = 20;
export const RESUME_DEFAULT_SCAN_LIMIT = 500;
export const RESUME_MAX_SCAN_LIMIT = 10000;

const RESUME_MAX_CANDIDATES = 20;
const RESUME_MAX_ACCEPTANCE_REFERENCES = 50;
const RESUME_TEXT_LIMITS = Object.freeze({
  short: 256,
  text: 500,
  path: 1024,
  commitSubject: 240,
  commitMetadata: 300,
  warning: 500,
});

export const TASK_ID_RE = /^T-\d{3}$/;
export const MILESTONE_ID_RE = /^M-\d{3}$/;
export const FEATURE_ID_RE = /^F-\d{3}$/;
export const TASK_STATUS = new Set(['planned', 'in-progress', 'blocked', 'done', 'archived']);
const BUNDLE_STATUS = new Set(['planned', 'in-progress', 'blocked', 'done']);
export const MILESTONE_STATUS = new Set(['planned', 'in-progress', 'blocked', 'done']);
export const FEATURE_STATUS = new Set(['planned', 'in-progress', 'blocked', 'done', 'cut']);

export function toPosix(value) {
  return String(value).replace(/\\/g, '/');
}

export function normalizeEol(value) {
  return String(value || '').replace(/\r\n/g, '\n');
}

function markdownCell(value) {
  return String(value || '').replace(/\r?\n/g, ' ').replace(/\|/g, '\\|');
}

export function getAutoGeneratedContent(raw, blockId) {
  if (raw === null || raw === undefined) return null;
  const normalized = normalizeEol(raw);
  const start = `<!-- AUTO-GENERATED:START ${blockId} -->`;
  const end = `<!-- AUTO-GENERATED:END ${blockId} -->`;
  const startIndex = normalized.indexOf(start);
  const endIndex = normalized.indexOf(end);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) return null;
  return normalized.slice(startIndex + start.length, endIndex).trim();
}

export function renderDashboardProjection(registry) {
  const tasks = Array.isArray(registry?.tasks) ? registry.tasks : [];
  const counts = { planned: 0, inProgress: 0, blocked: 0, done: 0, archived: 0 };
  for (const task of tasks) {
    const status = String(task?.status || '');
    if (status === 'planned') counts.planned++;
    else if (status === 'in-progress') counts.inProgress++;
    else if (status === 'blocked') counts.blocked++;
    else if (status === 'done') counts.done++;
    else if (status === 'archived') counts.archived++;
  }
  return [
    '## Summary',
    '',
    `- Tasks: ${tasks.length} (planned: ${counts.planned}, in-progress: ${counts.inProgress}, blocked: ${counts.blocked}, done: ${counts.done}, archived: ${counts.archived})`,
    '',
    '## Recently registered or status-changed tasks',
    '',
    '| Task | Status | Feature | Dev Docs |',
    '| --- | --- | --- | --- |',
    ...tasks
      .slice()
      .sort((left, right) => String(right?.updated || '').localeCompare(String(left?.updated || '')))
      .slice(0, 20)
      .map((task) => {
        const label = `${task?.id || ''} ${task?.slug || ''}`.trim();
        return `| ${markdownCell(label)} | ${markdownCell(task?.status)} | ${markdownCell(task?.feature_id)} | ${markdownCell(task?.dev_docs_path)} |`;
      }),
    '',
  ].join('\n');
}

export function renderFeatureMap(registry) {
  const tasks = Array.isArray(registry?.tasks) ? registry.tasks : [];
  const features = Array.isArray(registry?.features) ? registry.features : [];
  const milestones = Array.isArray(registry?.milestones) ? registry.milestones : [];
  const tasksByFeature = new Map();
  for (const task of tasks) {
    const featureId = String(task?.feature_id || 'F-000');
    const grouped = tasksByFeature.get(featureId) || [];
    grouped.push(task);
    tasksByFeature.set(featureId, grouped);
  }

  const lines = ['# Feature Map', '', '<!-- AUTO-GENERATED:START feature-map -->'];
  for (const milestone of milestones.slice().sort((a, b) => String(a?.id || '').localeCompare(String(b?.id || '')))) {
    if (!milestone || typeof milestone !== 'object') continue;
    const milestoneId = String(milestone.id || '');
    lines.push(`## ${milestoneId} ${markdownCell(milestone.title)}`.trim(), '');
    lines.push(`- Status: ${markdownCell(milestone.status)}`);
    lines.push(`- Description: ${markdownCell(milestone.description) || '_No description recorded._'}`, '');
    const ownedFeatures = features
      .filter((feature) => feature && String(feature.milestone_id || '') === milestoneId)
      .sort((a, b) => String(a.id || '').localeCompare(String(b.id || '')));
    if (ownedFeatures.length === 0) {
      lines.push('_No Features._', '');
      continue;
    }
    for (const feature of ownedFeatures) {
      const featureId = String(feature.id || '');
      lines.push(`### ${featureId} ${markdownCell(feature.title)}`.trim(), '');
      lines.push(`- Status: ${markdownCell(feature.status)}`);
      lines.push(`- Description: ${markdownCell(feature.description) || '_No description recorded._'}`, '');
      const mappedTasks = (tasksByFeature.get(featureId) || [])
        .slice()
        .sort((a, b) => String(a?.id || '').localeCompare(String(b?.id || '')));
      if (mappedTasks.length === 0) {
        lines.push('- (no tasks)', '');
        continue;
      }
      lines.push('| Task | Status | Dev Docs |', '| --- | --- | --- |');
      for (const task of mappedTasks) {
        const label = `${task?.id || ''} ${task?.slug || ''}`.trim();
        lines.push(
          `| ${markdownCell(label)} | ${markdownCell(task?.status)} | ${markdownCell(task?.dev_docs_path)} |`
        );
      }
      lines.push('');
    }
  }
  lines.push('<!-- AUTO-GENERATED:END feature-map -->', '');
  return lines.join('\n');
}

export function readText(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
}

export function exists(filePath) {
  try {
    return fs.existsSync(filePath);
  } catch {
    return false;
  }
}

export function canonicalPath(filePath) {
  const resolved = path.resolve(filePath);
  try {
    return fs.realpathSync.native(resolved);
  } catch {
    return resolved;
  }
}

export function findRepoRoot(startDir) {
  let dir = path.resolve(startDir);
  while (true) {
    if (exists(path.join(dir, '.ai', 'project', 'AGENTS.md'))) return canonicalPath(dir);
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

export function getHubDir(repoRoot) {
  return path.join(repoRoot, '.ai', 'project');
}

export function getRegistryPath(repoRoot) {
  return path.join(getHubDir(repoRoot), 'registry.json');
}

function listImmediateChildDirs(dirPath) {
  let entries;
  try {
    entries = fs.readdirSync(dirPath, { withFileTypes: true });
  } catch (error) {
    // A directory that does not exist is a legitimate empty state (governance not installed
    // there yet). Any other failure is unreadable evidence and must not degrade to "empty".
    if (error?.code === 'ENOENT') return [];
    throw new Error(
      `Cannot read task-evidence directory ${toPosix(dirPath)}: ${error?.code || error?.message || error}.`
    );
  }
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort((a, b) => a.localeCompare(b));
}

export function getBundleStatusFromStatusDoc(statusRaw, statusPath = '01-status.md') {
  const lines = normalizeEol(statusRaw).split('\n');
  let inProgress = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('#')) {
      if (/^##\s+Progress\s*$/i.test(trimmed)) {
        inProgress = true;
        continue;
      }
      if (inProgress && /^##\s+/.test(trimmed)) break;
    }
    if (!inProgress) continue;

    const match = trimmed.match(/^\-\s*State\s*:\s*(.+)\s*$/i);
    if (!match) continue;
    const value = String(match[1] || '').trim();
    if (value.includes('|')) {
      return { status: null, error: 'State must be a single value (not an enum hint).' };
    }
    if (!BUNDLE_STATUS.has(value)) {
      const hint = BUNDLE_STATUS.has(value.toLowerCase()) ? ' (status values must be lowercase)' : '';
      return {
        status: null,
        error: `Invalid State value: "${value}". Allowed: ${[...BUNDLE_STATUS].join(', ')}${hint}`,
      };
    }
    return { status: value, error: null };
  }

  return {
    status: null,
    error: `Missing "## Progress" / "- State: <status>" in ${toPosix(statusPath)}.`,
  };
}

export function getMarkdownSectionLines(markdownRaw, heading) {
  const lines = normalizeEol(markdownRaw).split('\n');
  const target = String(heading || '').trim().toLowerCase();
  const result = [];
  let inSection = false;

  for (const line of lines) {
    const match = line.trim().match(/^##\s+(.+?)\s*$/);
    if (match) {
      if (inSection) break;
      inSection = String(match[1] || '').trim().toLowerCase() === target;
      continue;
    }
    if (inSection) result.push(line);
  }
  return result;
}

export function cleanMarkdownValue(value) {
  return String(value || '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join(' ')
    .trim();
}

function createResumeTextLimiter() {
  const fields = [];

  function mark(field) {
    if (!fields.includes(field)) fields.push(field);
  }

  function text(value, maxChars, field) {
    if (value === null || value === undefined) return value;
    const raw = String(value);
    if (raw.length <= maxChars) return raw;
    mark(field);
    return `${raw.slice(0, Math.max(0, maxChars - 1))}…`;
  }

  return { fields, mark, text };
}

function getMarkdownSectionText(markdownRaw, heading) {
  return cleanMarkdownValue(getMarkdownSectionLines(markdownRaw, heading).join('\n'));
}

function getMarkdownListField(markdownRaw, heading, field) {
  const target = String(field || '').trim().toLowerCase();
  for (const line of getMarkdownSectionLines(markdownRaw, heading)) {
    const match = line.trim().match(/^\-\s*([^:]+)\s*:\s*(.*)$/);
    if (!match || String(match[1] || '').trim().toLowerCase() !== target) continue;
    return cleanMarkdownValue(match[2] || '');
  }
  return '';
}

function parseTableRowCells(line) {
  const trimmed = String(line || '').trim();
  if (!trimmed.startsWith('|') || !trimmed.endsWith('|')) return null;
  // Split on unescaped pipes only: `\|` is literal cell content and `\\|` is a literal
  // backslash followed by a cell boundary, matching how markdownCell escapes on render.
  const cells = [];
  let current = '';
  for (let index = 1; index < trimmed.length - 1; index++) {
    const char = trimmed[index];
    if (char === '\\' && index + 1 < trimmed.length - 1) {
      const next = trimmed[index + 1];
      current += next === '|' ? '|' : char + next;
      index++;
      continue;
    }
    if (char === '|') {
      cells.push(current.trim());
      current = '';
      continue;
    }
    current += char;
  }
  cells.push(current.trim());
  return cells;
}

function isTableSeparatorRow(cells) {
  return cells !== null && cells.length > 0 && cells.every((cell) => /^:?-{3,}:?$/.test(cell));
}

function getPitfallTableItems(markdownRaw, limit) {
  // The header is structural — any table row directly followed by a separator row — so template
  // display wording cannot break parsing. Data columns follow the current template order:
  // hazard, evidence, prevention, removal condition.
  const items = [];
  const lines = normalizeEol(markdownRaw).split('\n');
  let inTable = false;

  for (let index = 0; index < lines.length; index++) {
    const cells = parseTableRowCells(lines[index]);
    if (cells === null) {
      inTable = false;
      continue;
    }
    if (!inTable) {
      if (isTableSeparatorRow(parseTableRowCells(lines[index + 1]))) {
        inTable = true;
        index++;
      }
      continue;
    }
    const hazard = cleanMarkdownValue(cells[0]);
    if (!hazard) continue;
    const prevention = cleanMarkdownValue(cells[2]);
    items.push(prevention ? `${hazard} — ${prevention}` : hazard);
    if (items.length >= limit) break;
  }
  return items;
}

function getMarkdownChecklistStats(markdownRaw, heading) {
  const items = getMarkdownChecklistItems(markdownRaw, heading);
  return {
    total: items.length,
    checked: items.filter((item) => item.checked).length,
  };
}

export function getMarkdownChecklistItems(markdownRaw, heading) {
  const items = [];
  for (const line of getMarkdownSectionLines(markdownRaw, heading)) {
    const match = line.trim().match(/^\-\s*\[(x|X|\s)\]\s+(.+)$/);
    if (!match) continue;
    const text = cleanMarkdownValue(match[2]);
    if (!text) continue;
    items.push({ checked: String(match[1]).toLowerCase() === 'x', text });
  }
  return items;
}

export function getRoadmapKickoff(roadmapRaw) {
  const status = getMarkdownListField(roadmapRaw, 'Kickoff gate', 'Status').toLowerCase();
  return {
    status: status === 'pending' || status === 'ready' ? status : '',
    rawStatus: status,
    ...getMarkdownChecklistStats(roadmapRaw, 'Kickoff gate'),
  };
}

export function formatTaskRef(task) {
  return `${task.taskId || '(no-id)'} ${task.slug} (${task.phase}) @ ${toPosix(task.relPath)}`;
}

export function loadRegistry(repoRoot) {
  const registryPath = getRegistryPath(repoRoot);
  const raw = readText(registryPath);
  if (raw === null) return { path: registryPath, registry: null, error: null };
  if (!raw.trim()) return { path: registryPath, registry: null, error: 'registry.json is empty.' };

  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      throw new Error('Registry root must be a JSON object.');
    }
    return { path: registryPath, registry: parsed, error: null };
  } catch (error) {
    return { path: registryPath, registry: null, error: error.message || String(error) };
  }
}

function getFeatureMilestoneMap(registry) {
  return new Map(
    (Array.isArray(registry?.features) ? registry.features : [])
      .filter((feature) => feature && typeof feature === 'object')
      .map((feature) => [String(feature.id || ''), String(feature.milestone_id || '')])
  );
}

function resolveTaskStatusDoc(taskDir) {
  return path.join(taskDir, '01-status.md');
}

function resolveTaskRoadmapDoc(taskDir) {
  return path.join(taskDir, '00-roadmap.md');
}

function resolveTaskPitfallsDoc(taskDir) {
  return path.join(taskDir, 'pitfalls.md');
}

export function scanTasks(repoRoot) {
  const tasks = [];
  const root = path.join(repoRoot, 'dev-docs');
  for (const phase of ['active', 'archive']) {
    const phaseDir = path.join(root, phase);
    for (const slug of listImmediateChildDirs(phaseDir)) {
      const taskDir = path.join(phaseDir, slug);
      tasks.push({
        root,
        phase,
        slug,
        absPath: taskDir,
        relPath: path.relative(repoRoot, taskDir),
        statusPath: resolveTaskStatusDoc(taskDir),
        roadmapPath: resolveTaskRoadmapDoc(taskDir),
        metaPath: path.join(taskDir, '.ai-task.json'),
      });
    }
  }
  return tasks.sort((a, b) => a.relPath.localeCompare(b.relPath));
}

export function parseTaskMeta(metaRaw) {
  let parsed;
  try {
    parsed = JSON.parse(metaRaw);
  } catch (error) {
    return {
      version: null,
      task_id: '',
      slug: '',
      keywords: [],
      parse_error: error?.message || String(error),
      schema_errors: [],
    };
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return {
      version: null,
      task_id: '',
      slug: '',
      keywords: [],
      parse_error: null,
      schema_errors: ['Metadata root must be a JSON object.'],
    };
  }

  const map = parsed;
  const expected = ['version', 'task_id', 'slug', 'keywords'];
  const schemaErrors = [];
  for (const key of expected) {
    if (!Object.hasOwn(map, key)) schemaErrors.push(`Missing required field: "${key}".`);
  }
  for (const key of Object.keys(map)) {
    if (!expected.includes(key)) schemaErrors.push(`Unsupported field: "${key}".`);
  }
  if (map.version !== 1) schemaErrors.push('Field "version" must be 1.');
  if (typeof map.task_id !== 'string' || !TASK_ID_RE.test(map.task_id)) {
    schemaErrors.push('Field "task_id" must match T-###.');
  }
  if (typeof map.slug !== 'string' || !map.slug.trim()) {
    schemaErrors.push('Field "slug" must be a non-empty string.');
  }
  if (!Array.isArray(map.keywords)) {
    schemaErrors.push('Field "keywords" must be an array of unique non-empty strings.');
  } else {
    const normalized = map.keywords.map((value) => typeof value === 'string' ? value.trim() : '');
    if (
      normalized.some((value) => !value) ||
      map.keywords.some((value, index) => value !== normalized[index]) ||
      new Set(normalized).size !== normalized.length
    ) {
      schemaErrors.push('Field "keywords" must be an array of unique non-empty strings.');
    }
  }
  return {
    version: map.version,
    task_id: typeof map.task_id === 'string' ? map.task_id : '',
    slug: typeof map.slug === 'string' ? map.slug : '',
    keywords: Array.isArray(map.keywords)
      ? map.keywords.filter((value) => typeof value === 'string').map((value) => value.trim())
      : [],
    parse_error: null,
    schema_errors: schemaErrors,
  };
}

function formatJsonLines(rows) {
  for (const row of rows) console.log(JSON.stringify(row));
}

function collectBundleTaskRows({ repoRoot }) {
  const rows = [];

  for (const task of scanTasks(repoRoot)) {
    const statusRaw = readText(task.statusPath);
    const roadmapRaw = readText(task.roadmapPath);
    const metaRaw = readText(task.metaPath);
    const effectiveStatus = task.phase === 'archive'
      ? 'archived'
      : (() => {
          if (!statusRaw) return '';
          return getBundleStatusFromStatusDoc(statusRaw, path.basename(task.statusPath)).status || '';
        })();

    let taskId = '';
    let keywords = [];
    let metaInvalid = false;
    let metaErrors = [];
    if (metaRaw !== null) {
      const meta = parseTaskMeta(metaRaw);
      if (TASK_ID_RE.test(meta.task_id)) taskId = meta.task_id;
      metaErrors = meta.parse_error ? [meta.parse_error] : meta.schema_errors;
      metaInvalid = metaErrors.length > 0;
      if (!metaInvalid) {
        keywords = meta.keywords;
      }
    }

    rows.push({
      id: taskId,
      status: effectiveStatus,
      slug: task.slug,
      dev_docs_path: toPosix(task.relPath),
      goal: getMarkdownSectionText(statusRaw, 'Goal'),
      keywords: keywords.map((keyword) => String(keyword)),
      meta_missing: metaRaw === null,
      meta_invalid: metaInvalid,
      meta_errors: metaErrors,
      status_doc_state:
        task.phase === 'archive' ? 'not-required' : statusRaw !== null ? 'present' : 'missing',
      status_doc_path: toPosix(path.relative(repoRoot, task.statusPath)),
      roadmap_path: toPosix(path.relative(repoRoot, task.roadmapPath)),
      kickoff_status:
        task.phase === 'archive' ? 'not-required' : getRoadmapKickoff(roadmapRaw).status || 'unknown',
    });
  }

  return rows.sort((a, b) => String(a.id || '').localeCompare(String(b.id || '')));
}

function collectAllWorktreeTaskOccurrences(repoRoot) {
  const rows = [];
  for (const worktree of listGitWorktrees(repoRoot)) {
    const registry = loadRegistry(worktree.path).registry;
    const featureMilestones = getFeatureMilestoneMap(registry);
    const registryTasks = new Map(
      (Array.isArray(registry?.tasks) ? registry.tasks : [])
        .filter((task) => task && typeof task === 'object' && TASK_ID_RE.test(String(task.id || '')))
        .map((task) => [String(task.id), task])
    );

    for (const task of collectBundleTaskRows({ repoRoot: worktree.path })) {
      const projection = registryTasks.get(task.id) || {};
      rows.push({
        feature_id: String(projection.feature_id || ''),
        milestone_id: featureMilestones.get(String(projection.feature_id || '')) || '',
        ...task,
        worktree_path: toPosix(worktree.path),
        worktree_branch: worktree.branch,
      });
    }
  }

  return rows.sort((a, b) => {
    const byId = String(a.id || '').localeCompare(String(b.id || ''));
    return byId || String(a.worktree_path || '').localeCompare(String(b.worktree_path || ''));
  });
}

const QUERY_FACT_FIELDS = [
  'status',
  'slug',
  'dev_docs_path',
  'feature_id',
  'milestone_id',
  'goal',
  'keywords',
  'meta_missing',
  'status_doc_state',
  'status_doc_path',
  'roadmap_path',
  'kickoff_status',
];

const PROJECTION_FACT_FIELDS = new Set(['feature_id', 'milestone_id']);

/**
 * Object at a path inside a commit, distinguishing "absent at this commit" (`ok` with a null id)
 * from "evidence unreadable" (`ok: false`). Fail-closed callers must treat unreadable evidence as
 * a stop, never as an empty state.
 */
function readGitCommitPathObject(repoRoot, sha, relPath) {
  const raw = runGit(repoRoot, ['ls-tree', sha, '--', toPosix(relPath)]);
  if (raw === null) return { ok: false, id: null };
  const line = raw.split('\n').find((item) => item.trim());
  if (!line) return { ok: true, id: null };
  const id = line.split(/\s+/)[2] || null;
  return id ? { ok: true, id } : { ok: false, id: null };
}

function listBundleFiles(absDir) {
  const out = [];
  function walk(dir, prefix) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(path.join(dir, entry.name), rel);
      else if (entry.isFile()) out.push(rel);
    }
  }
  try {
    walk(absDir, '');
  } catch {
    return null;
  }
  return out.sort();
}

/**
 * Content digest of a bundle as it exists in a worktree right now, uncommitted edits included.
 * Hashing goes through `git hash-object` so checkout filters (e.g. CRLF) cannot make a clean
 * file look modified. Returns '' for an absent/empty bundle and null when evidence is unreadable.
 */
function worktreeBundleDigest(worktreePath, relPath) {
  const files = listBundleFiles(path.join(worktreePath, relPath));
  if (files === null) return null;
  if (files.length === 0) return '';
  // Paths go through stdin so a bundle with many artifacts cannot exceed the platform's
  // command-line length limit.
  const raw = runGit(worktreePath, ['hash-object', '--stdin-paths'], {
    input: `${files.map((file) => toPosix(path.join(relPath, file))).join('\n')}\n`,
  });
  if (raw === null) return null;
  const oids = raw.split('\n').map((line) => line.trim()).filter(Boolean);
  if (oids.length !== files.length) return null;
  return files.map((file, index) => `${file}:${oids[index]}`).join('\n');
}

/**
 * Content digest of a bundle inside a commit. Returns '' when the path is absent at that commit
 * and null when the evidence is unreadable.
 */
function committedBundleDigest(repoRoot, sha, relPath) {
  const posix = toPosix(relPath);
  const raw = runGit(repoRoot, ['ls-tree', '-r', sha, '--', posix]);
  if (raw === null) return null;
  const lines = [];
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    const match = line.match(/^\S+ \S+ (\S+)\t(.+)$/);
    if (!match) return null;
    const [, oid, fullPath] = match;
    if (!fullPath.startsWith(`${posix}/`)) return null;
    lines.push(`${fullPath.slice(posix.length + 1)}:${oid}`);
  }
  return lines.sort().join('\n');
}

function serializeTaskProjection(featureId, milestoneId) {
  return `${featureId || ''}\u0000${milestoneId || ''}`;
}

function readTaskProjectionAt(repoRoot, sha, taskId) {
  const object = readGitCommitPathObject(repoRoot, sha, '.ai/project/registry.json');
  if (!object.ok) return { ok: false, projection: '' };
  if (object.id === null) return { ok: true, projection: serializeTaskProjection('', '') };
  const raw = runGit(repoRoot, ['cat-file', 'blob', object.id]);
  if (raw === null) return { ok: false, projection: '' };
  try {
    const parsed = JSON.parse(raw);
    const tasks = Array.isArray(parsed?.tasks) ? parsed.tasks : [];
    const entry = tasks.find((task) => task && String(task.id || '') === taskId) || null;
    if (!entry) return { ok: true, projection: serializeTaskProjection('', '') };
    const features = Array.isArray(parsed?.features) ? parsed.features : [];
    const feature =
      features.find((item) => item && String(item.id || '') === String(entry.feature_id || '')) ||
      null;
    return {
      ok: true,
      projection: serializeTaskProjection(entry.feature_id, feature?.milestone_id),
    };
  } catch {
    return { ok: false, projection: '' };
  }
}

function taskOccurrenceRef(occurrence) {
  return {
    worktree_path: occurrence.worktree_path,
    worktree_branch: occurrence.worktree_branch,
    dev_docs_path: occurrence.dev_docs_path,
  };
}

/**
 * Resolve divergent task copies when Git proves linear evolution: since each merge base only one
 * side changed (counting uncommitted edits), the newest occurrence supplies the row. Freshness is
 * judged on full bundle content plus the registry projection — not only on query facts — so an
 * evolution that lives only in roadmap, architecture, verification, or supporting documents still
 * routes to the newest copy. Content-equal copies are interchangeable co-leaders, never stale.
 *
 * Returns { equal: true } when every occurrence carries the same content and { leader, stale }
 * when one provable line of evolution exists. Everything else stays fail-closed and returns
 * { failure } with a reason (`concurrent-divergence`, `unrelated-history`, `missing-lineage`, or
 * `unreadable-evidence`), the content-equivalence `groups` when they were readable, and the
 * implicated `evidence` occurrences with the stage that failed.
 */
function resolveStaleTaskOccurrences(repoRoot, taskId, ordered, conflicts) {
  const projectionConflicted = conflicts.some((item) => PROJECTION_FACT_FIELDS.has(item.field));

  const states = [];
  for (const occurrence of ordered) {
    const currentBundle = worktreeBundleDigest(occurrence.worktree_path, occurrence.dev_docs_path);
    if (currentBundle === null || currentBundle === '') {
      return {
        failure: {
          reason: 'unreadable-evidence',
          evidence: [{ ...taskOccurrenceRef(occurrence), stage: 'worktree-content' }],
        },
      };
    }
    const currentProjection = serializeTaskProjection(
      occurrence.feature_id,
      occurrence.milestone_id
    );
    states.push({
      occurrence,
      currentBundle,
      currentProjection,
      key: `${currentBundle}\u0000${projectionConflicted ? currentProjection : ''}`,
    });
  }

  const groupsByKey = new Map();
  for (const state of states) {
    const group = groupsByKey.get(state.key) || {
      value: `content:${crypto.createHash('sha256').update(state.key).digest('hex').slice(0, 12)}`,
      worktrees: [],
    };
    group.worktrees.push(taskOccurrenceRef(state.occurrence));
    groupsByKey.set(state.key, group);
  }
  const groups = [...groupsByKey.values()];
  const failWith = (reason, evidence) => ({
    failure: { reason, groups, ...(evidence ? { evidence } : {}) },
  });

  if (groups.length === 1) return { equal: true };

  for (const state of states) {
    const headRaw = runGit(state.occurrence.worktree_path, ['rev-parse', 'HEAD']);
    if (!headRaw?.trim()) {
      return failWith('unreadable-evidence', [
        { ...taskOccurrenceRef(state.occurrence), stage: 'head-commit' },
      ]);
    }
    state.head = headRaw.trim();
    const headBundle = committedBundleDigest(repoRoot, state.head, state.occurrence.dev_docs_path);
    if (headBundle === null) {
      return failWith('unreadable-evidence', [
        { ...taskOccurrenceRef(state.occurrence), stage: 'head-bundle' },
      ]);
    }
    // A bundle absent from its own HEAD has no provable lineage.
    if (headBundle === '') {
      return failWith('missing-lineage', [
        { ...taskOccurrenceRef(state.occurrence), stage: 'head-bundle' },
      ]);
    }
    if (projectionConflicted) {
      const headProjection = readTaskProjectionAt(repoRoot, state.head, taskId);
      if (!headProjection.ok) {
        return failWith('unreadable-evidence', [
          { ...taskOccurrenceRef(state.occurrence), stage: 'head-projection' },
        ]);
      }
      state.headProjection = headProjection.projection;
    }
  }

  // { sha } on success, { reason } when there is no common ancestor or the command fails.
  function mergeBaseEvidence(left, right) {
    if (left === right) return { sha: left };
    const result = runGitWithStatus(repoRoot, ['merge-base', left, right]);
    if (result.status === 0 && result.stdout.trim()) return { sha: result.stdout.trim() };
    if (result.status === 1) return { reason: 'unrelated-history' };
    return { reason: 'unreadable-evidence' };
  }

  // true / false, or { stage } when the evidence is unreadable. Content comparison against the
  // merge base covers committed evolution and uncommitted edits in one check.
  function changedSince(state, baseSha) {
    const baseBundle = committedBundleDigest(repoRoot, baseSha, state.occurrence.dev_docs_path);
    if (baseBundle === null) return { stage: 'base-bundle' };
    if (state.currentBundle !== baseBundle) return true;
    if (projectionConflicted) {
      if (state.currentProjection !== state.headProjection) return true;
      const baseProjection = readTaskProjectionAt(repoRoot, baseSha, taskId);
      if (!baseProjection.ok) return { stage: 'base-projection' };
      if (state.headProjection !== baseProjection.projection) return true;
    }
    return false;
  }

  const leaders = [];
  for (const candidate of states) {
    let dominates = true;
    for (const other of states) {
      if (other === candidate) continue;
      // A content-equal copy is an interchangeable co-leader; it does not need to be dominated.
      if (other.key === candidate.key) continue;
      const base = mergeBaseEvidence(candidate.head, other.head);
      if (base.reason) {
        return failWith(base.reason, [
          { ...taskOccurrenceRef(candidate.occurrence), stage: 'merge-base' },
          { ...taskOccurrenceRef(other.occurrence), stage: 'merge-base' },
        ]);
      }
      const otherChanged = changedSince(other, base.sha);
      if (otherChanged !== true && otherChanged !== false) {
        return failWith('unreadable-evidence', [
          { ...taskOccurrenceRef(other.occurrence), stage: otherChanged.stage },
        ]);
      }
      if (otherChanged) {
        dominates = false;
        break;
      }
    }
    if (dominates) leaders.push(candidate);
  }
  if (leaders.length === 0 || new Set(leaders.map((state) => state.key)).size > 1) {
    return failWith('concurrent-divergence');
  }

  const currentRoot = canonicalPath(repoRoot);
  const leader =
    leaders.find((state) => canonicalPath(state.occurrence.worktree_path) === currentRoot) ||
    leaders[0];
  return {
    leader: leader.occurrence,
    stale: states
      .filter((state) => state.key !== leader.key)
      .map((state) => state.occurrence),
  };
}

function normalizeQueryFact(field, value) {
  if (field === 'keywords') {
    return [...new Set(Array.isArray(value) ? value.map((item) => String(item)) : [])].sort();
  }
  return value === undefined ? null : value;
}

function mergeTaskOccurrences(repoRoot, rows) {
  const groups = new Map();
  for (const row of rows) {
    const id = String(row.id || '');
    const key = TASK_ID_RE.test(id)
      ? `task:${id}`
      : `occurrence:${row.worktree_path}\u0000${row.dev_docs_path}`;
    const group = groups.get(key) || [];
    group.push(row);
    groups.set(key, group);
  }

  const currentRoot = canonicalPath(repoRoot);
  const merged = [];
  for (const group of groups.values()) {
    const ordered = group.slice().sort((left, right) => {
      const leftCurrent = canonicalPath(left.worktree_path) === currentRoot ? 0 : 1;
      const rightCurrent = canonicalPath(right.worktree_path) === currentRoot ? 0 : 1;
      return leftCurrent - rightCurrent
        || String(left.worktree_path).localeCompare(String(right.worktree_path))
        || String(left.dev_docs_path).localeCompare(String(right.dev_docs_path));
    });
    let representative = ordered[0];
    const result = { id: String(representative.id || '') };
    let conflicts = [];

    for (const field of QUERY_FACT_FIELDS) {
      const values = new Map();
      for (const occurrence of ordered) {
        const value = normalizeQueryFact(field, occurrence[field]);
        const key = JSON.stringify(value);
        const entry = values.get(key) || { value, worktrees: [] };
        entry.worktrees.push({
          worktree_path: occurrence.worktree_path,
          worktree_branch: occurrence.worktree_branch,
          dev_docs_path: occurrence.dev_docs_path,
        });
        values.set(key, entry);
      }

      if (values.size === 1) {
        result[field] = [...values.values()][0].value;
      } else {
        result[field] = null;
        conflicts.push({ field, values: [...values.values()] });
      }
    }

    result.stale_worktrees = [];
    const anyInvalid = ordered.some((occurrence) => occurrence.meta_invalid);
    if (ordered.length > 1 && !anyInvalid && TASK_ID_RE.test(result.id)) {
      // Freshness is judged on full bundle content, not only on query facts, for every
      // multi-occurrence task: a provable single line of evolution routes the row to its newest
      // occurrence; anything unprovable stays fail-closed.
      const resolution = resolveStaleTaskOccurrences(repoRoot, result.id, ordered, conflicts);
      if (resolution.leader) {
        for (const field of QUERY_FACT_FIELDS) {
          result[field] = normalizeQueryFact(field, resolution.leader[field]);
        }
        conflicts = [];
        representative = resolution.leader;
        result.stale_worktrees = resolution.stale.map(taskOccurrenceRef);
      } else if (resolution.failure && conflicts.length === 0) {
        // The divergence lives only in non-query documents (or its evidence is unreadable).
        // Surface it as a conflict with actionable diagnostics instead of silently choosing a
        // copy: the reason says whether to coordinate concurrent edits or repair evidence, the
        // groups say which worktrees carry equivalent content, and the evidence entries name the
        // occurrence and stage that could not be read.
        const failure = resolution.failure;
        conflicts = [
          {
            field: 'documents',
            reason: failure.reason,
            values: failure.groups || [
              { value: 'unverifiable-content', worktrees: ordered.map(taskOccurrenceRef) },
            ],
            ...(failure.evidence ? { evidence: failure.evidence } : {}),
          },
        ];
      }
    }

    result.conflict = conflicts.length > 0;
    result.conflicts = conflicts;
    result.invalid = anyInvalid;
    result.metadata_errors = ordered
      .filter((occurrence) => occurrence.meta_invalid)
      .map((occurrence) => ({
        worktree_path: occurrence.worktree_path,
        dev_docs_path: occurrence.dev_docs_path,
        errors: occurrence.meta_errors,
      }));
    result.occurrence_count = ordered.length;
    result.worktrees = ordered.map((occurrence) => ({
      worktree_path: occurrence.worktree_path,
      worktree_branch: occurrence.worktree_branch,
      dev_docs_path: occurrence.dev_docs_path,
    }));
    result.worktree_path = result.conflict ? null : representative.worktree_path;
    result.worktree_branch = result.conflict ? null : representative.worktree_branch;
    merged.push(result);
  }

  return merged.sort((left, right) => {
    const byId = String(left.id || '').localeCompare(String(right.id || ''));
    return byId || String(left.dev_docs_path || '').localeCompare(String(right.dev_docs_path || ''));
  });
}

export function queryTasks({ repoRoot, id = null, status = null, text = null }) {
  function includesText(value, needle) {
    if (!needle) return true;
    return String(value || '').toLowerCase().includes(String(needle).toLowerCase());
  }

  function taskMatches(task) {
    if (id && String(task.id || '') !== id) return false;
    if (status && String(task.status || '').trim() !== status) {
      const conflict = (task.conflicts || []).find((item) => item.field === 'status');
      if (!conflict?.values.some((entry) => entry.value === status)) return false;
    }
    if (text) {
      const parts = [];
      for (const field of [
        'id', 'slug', 'goal', 'status', 'dev_docs_path',
        'feature_id', 'milestone_id', 'worktree_path', 'worktree_branch',
      ]) {
        parts.push(String(task[field] || ''));
      }
      if (Array.isArray(task.keywords)) parts.push(task.keywords.join(' '));
      if (task.conflict) parts.push(JSON.stringify(task.conflicts));
      parts.push(JSON.stringify(task.worktrees || []));
      if (!includesText(parts.join('\n'), text)) return false;
    }
    return true;
  }

  return mergeTaskOccurrences(repoRoot, collectAllWorktreeTaskOccurrences(repoRoot)).filter(taskMatches);
}

export function cmdQuery({ repoRoot, id, status, text, json }) {
  const rows = queryTasks({ repoRoot, id, status, text });
  if (json) console.log(JSON.stringify(rows));
  else formatJsonLines(rows);
  return { ok: true, rows };
}

const ACTIVE_TASK_STATUS = new Set(['in-progress', 'blocked']);

function resolveTaskContext({ repoRoot, taskId }) {
  const rows = collectBundleTaskRows({ repoRoot }).filter((row) => TASK_ID_RE.test(String(row.id || '')));
  if (taskId) {
    const found = rows.find((row) => row.id === taskId);
    if (!found) return { ok: false, reason: 'not-found', candidates: [] };
    return { ok: true, task: found, candidates: [found] };
  }

  const inProgress = rows.filter((row) => row.status === 'in-progress');
  const pool = inProgress.length > 0 ? inProgress : rows.filter((row) => ACTIVE_TASK_STATUS.has(row.status));
  if (pool.length === 1) return { ok: true, task: pool[0], candidates: pool };
  if (pool.length === 0) return { ok: false, reason: 'none', candidates: [] };
  return { ok: false, reason: 'ambiguous', candidates: pool };
}

function taskIdsFromBranch(branch) {
  return [...new Set(String(branch || '').match(/T-\d{3}/g) || [])];
}

function resolveResumeTaskContext({ repoRoot, taskId, branch }) {
  function verifyOccurrence(localResult, source, missingReason, requestedId) {
    if (!localResult.ok && localResult.reason !== 'not-found') {
      return { ...localResult, source, branch };
    }
    const id = localResult.ok ? localResult.task.id : requestedId;
    const [global] = queryTasks({ repoRoot, id });
    if (!global) {
      return {
        ok: false,
        reason: missingReason,
        source,
        branch,
        branchTaskIds: source === 'branch' ? [id] : [],
        candidates: [],
      };
    }
    if (global.conflict) {
      return { ok: false, reason: 'conflict', source, branch, candidates: [global] };
    }
    if (global.invalid) {
      return { ok: false, reason: 'invalid-metadata', source, branch, candidates: [global] };
    }
    if (canonicalPath(global.worktree_path) !== canonicalPath(repoRoot)) {
      return { ok: false, reason: 'other-worktree', source, branch, candidates: [global] };
    }
    if (!localResult.ok) {
      return { ok: false, reason: missingReason, source, branch, candidates: [] };
    }
    return { ...localResult, source, branch };
  }

  if (taskId) {
    return verifyOccurrence(resolveTaskContext({ repoRoot, taskId }), 'explicit', 'not-found', taskId);
  }

  const branchTaskIds = taskIdsFromBranch(branch);
  if (branchTaskIds.length > 1) {
    return { ok: false, reason: 'branch-ambiguous', source: 'branch', branch, branchTaskIds, candidates: [] };
  }
  if (branchTaskIds.length === 1) {
    const branchTaskId = branchTaskIds[0];
    return verifyOccurrence(
      resolveTaskContext({ repoRoot, taskId: branchTaskId }),
      'branch',
      'branch-task-not-found',
      branchTaskId
    );
  }
  const active = resolveTaskContext({ repoRoot, taskId: null });
  if (!active.ok) return { ...active, source: 'active', branch };
  return verifyOccurrence(active, 'active', 'not-found', active.task.id);
}

function docsTrailerValue(devDocsPath) {
  const value = toPosix(String(devDocsPath || '')).replace(/\/+$/, '');
  return value ? `${value}/` : '';
}

export function runGit(repoRoot, args, { input } = {}) {
  try {
    return execFileSync('git', args, {
      cwd: repoRoot,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
      stdio: [input === undefined ? 'ignore' : 'pipe', 'pipe', 'ignore'],
      ...(input === undefined ? {} : { input }),
    });
  } catch {
    return null;
  }
}

/**
 * Like runGit but preserves the exit status, for callers that must distinguish a meaningful
 * non-zero answer (e.g. `merge-base` finding no common ancestor) from a failing command.
 */
function runGitWithStatus(repoRoot, args) {
  try {
    const stdout = execFileSync('git', args, {
      cwd: repoRoot,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return { status: 0, stdout };
  } catch (error) {
    return {
      status: typeof error?.status === 'number' ? error.status : null,
      stdout: typeof error?.stdout === 'string' ? error.stdout : '',
    };
  }
}

export function listGitWorktrees(repoRoot) {
  // Worktree enumeration is the entry point for every cross-worktree fact. A failure here must
  // never degrade to "only the current worktree": that silently hides evidence from query,
  // dedupe, allocation, and prune.
  const raw = runGit(repoRoot, ['worktree', 'list', '--porcelain']);
  if (!raw || !raw.trim()) {
    throw new Error('Cannot enumerate linked worktrees: `git worktree list --porcelain` failed.');
  }

  const worktrees = [];
  let current = null;
  for (const line of normalizeEol(raw).split('\n')) {
    if (line.startsWith('worktree ')) {
      if (current) worktrees.push(current);
      current = {
        path: canonicalPath(path.resolve(repoRoot, line.slice('worktree '.length))),
        branch: '(detached)',
      };
      continue;
    }
    if (current && line.startsWith('branch refs/heads/')) {
      current.branch = line.slice('branch refs/heads/'.length);
    }
  }
  if (current) worktrees.push(current);
  if (worktrees.length === 0) {
    throw new Error('Cannot enumerate linked worktrees: `git worktree list --porcelain` returned no entries.');
  }
  for (const worktree of worktrees) {
    if (!exists(worktree.path)) {
      throw new Error(
        `Linked worktree ${toPosix(worktree.path)} is registered but its directory is missing or ` +
          'unreadable. Repair or remove it (e.g. `git worktree prune`) before governance can trust ' +
          'cross-worktree evidence.'
      );
    }
  }
  return worktrees;
}

export function taskIdsFromAllWorktrees(repoRoot) {
  const ids = new Set();
  for (const worktree of listGitWorktrees(repoRoot)) {
    for (const task of scanTasks(worktree.path)) {
      const metaRaw = readText(task.metaPath);
      if (metaRaw === null) continue;
      const meta = parseTaskMeta(metaRaw);
      if (meta.parse_error || meta.schema_errors.length > 0) {
        const detail = meta.parse_error || meta.schema_errors.join(' ');
        throw new Error(
          `Invalid task metadata in linked worktree ${toPosix(worktree.path)} at ` +
            `${toPosix(task.relPath)}/.ai-task.json: ${detail}`
        );
      }
      ids.add(meta.task_id);
    }
  }
  return [...ids];
}

export function taskIdsFromAllBranches(repoRoot) {
  // A repository with no refs yet legitimately has no branch history; a failing Git command does
  // not. Only the former may be treated as an empty ID set.
  const refsRaw = runGit(repoRoot, ['for-each-ref', '--format=%(refname)']);
  if (refsRaw === null) {
    throw new Error('Cannot enumerate refs: `git for-each-ref` failed.');
  }
  if (!refsRaw.trim()) return [];

  const raw = runGit(repoRoot, ['log', '--all', '--format=%B']);
  if (raw === null) {
    throw new Error('Cannot read branch history: `git log --all` failed.');
  }
  const ids = new Set();
  for (const line of normalizeEol(raw).split('\n')) {
    const match = /^Task:[ \t]*(T-\d{3})[ \t]*$/.exec(line);
    if (match) ids.add(match[1]);
  }
  return [...ids];
}

function readCurrentBranch(repoRoot) {
  const raw = runGit(repoRoot, ['branch', '--show-current']);
  if (raw === null) return '';
  return raw.trim() || '(detached)';
}

function readHeadCommit(repoRoot) {
  const raw = runGit(repoRoot, ['rev-parse', '--short', 'HEAD']);
  return raw === null ? '' : raw.trim();
}

const COMMIT_FIELDS = [
  '%H', '%h', '%aI', '%an', '%s',
  '%(trailers:key=Task,valueonly,separator=%x2C)',
  '%(trailers:key=Phase,valueonly,separator=%x2C)',
  '%(trailers:key=Verify,valueonly,separator=%x2C)',
];

function readCommitTimeline({ repoRoot, scan }) {
  const raw = runGit(repoRoot, ['log', `--max-count=${scan}`, `--format=${COMMIT_FIELDS.join('%x1f')}%x1e`]);
  if (raw === null) {
    const insideWorktree = runGit(repoRoot, ['rev-parse', '--is-inside-work-tree']);
    const head = runGit(repoRoot, ['rev-parse', '--verify', 'HEAD']);
    if (insideWorktree?.trim() === 'true' && head === null) return [];
    return null;
  }

  const records = [];
  for (const chunk of raw.split('\x1e')) {
    const line = chunk.replace(/^\n/, '');
    if (!line.trim()) continue;
    const [sha, short, date, author, subject, task, phase, verify] = line.split('\x1f');
    records.push({
      commit: short || '',
      sha: sha || '',
      date: date || '',
      author: author || '',
      subject: subject || '',
      tasks: String(task || '').split(',').map((value) => value.trim()).filter(Boolean),
      phase: String(phase || '').trim(),
      verify: String(verify || '').trim(),
    });
  }
  return records;
}

function readWorktreeStatus(repoRoot, limit = 10) {
  const raw = runGit(repoRoot, ['status', '--porcelain=v1', '--untracked-files=all']);
  if (raw === null) return null;
  const allEntries = raw.split('\n').map((line) => line.trimEnd()).filter((line) => line.trim());
  return {
    clean: allEntries.length === 0,
    count: allEntries.length,
    entries: allEntries.slice(0, limit),
    truncated: allEntries.length > limit,
  };
}

function resumeFailureExitCode(reason) {
  if (
    reason === 'ambiguous' ||
    reason === 'branch-ambiguous' ||
    reason === 'conflict' ||
    reason === 'invalid-metadata'
  ) return 2;
  if (reason === 'none' || reason === 'not-found' || reason === 'branch-task-not-found') return 3;
  if (reason === 'other-worktree') return 4;
  return 1;
}

function resumeFailureMessage(result) {
  if (result.reason === 'branch-ambiguous') {
    return `Current branch contains multiple task IDs: ${result.branchTaskIds.join(', ')}`;
  }
  if (result.reason === 'branch-task-not-found') {
    return `Task from current branch was not found: ${result.branchTaskIds[0]}`;
  }
  if (result.reason === 'ambiguous') {
    return 'Multiple active tasks exist; pass --task <T-###> or use a branch containing one task ID.';
  }
  if (result.reason === 'not-found') return 'The requested task was not found.';
  if (result.reason === 'conflict') {
    return 'The requested task has conflicting facts across linked worktrees; reconcile them before resuming.';
  }
  if (result.reason === 'other-worktree') {
    return 'The requested task\u2019s bundle, or its newest state, is in another linked worktree; run recovery there or confirm a worktree change.';
  }
  if (result.reason === 'invalid-metadata') {
    return 'The requested task has invalid metadata in a linked worktree; repair that identity record before resuming.';
  }
  if (result.reason === 'none') return 'No active task was found; pass --task <T-###>.';
  if (result.reason === 'git-unavailable') return 'Unable to read Git history for context recovery.';
  return 'Unable to resolve a task for context recovery.';
}

function renderResumeFailure(result) {
  const limiter = createResumeTextLimiter();
  const allCandidates = Array.isArray(result.candidates) ? result.candidates : [];
  const branchTaskIds = Array.isArray(result.branchTaskIds)
    ? result.branchTaskIds.slice(0, RESUME_MAX_CANDIDATES)
    : [];
  if (Array.isArray(result.branchTaskIds) && result.branchTaskIds.length > RESUME_MAX_CANDIDATES) {
    limiter.mark('error.branch_task_ids');
  }
  if (allCandidates.length > RESUME_MAX_CANDIDATES) limiter.mark('error.candidates');

  function boundedValue(value, field) {
    const encoded = JSON.stringify(value);
    if (encoded === undefined || encoded.length <= RESUME_TEXT_LIMITS.text) return value;
    return limiter.text(encoded, RESUME_TEXT_LIMITS.text, field);
  }

  function boundedWorktree(worktree, field) {
    return {
      worktree_path: limiter.text(worktree.worktree_path, RESUME_TEXT_LIMITS.path, `${field}.worktree_path`),
      worktree_branch: limiter.text(worktree.worktree_branch, RESUME_TEXT_LIMITS.short, `${field}.worktree_branch`),
      dev_docs_path: limiter.text(worktree.dev_docs_path, RESUME_TEXT_LIMITS.path, `${field}.dev_docs_path`),
    };
  }

  const error = {
    reason: result.reason || 'unknown',
    message: limiter.text(resumeFailureMessage(result), RESUME_TEXT_LIMITS.warning, 'error.message'),
    branch: limiter.text(result.branch || '', RESUME_TEXT_LIMITS.short, 'error.branch'),
    branch_task_ids: branchTaskIds,
    candidates: allCandidates.slice(0, RESUME_MAX_CANDIDATES).map((candidate, index) => {
      const field = `error.candidates[${index}]`;
      if ((candidate.worktrees || []).length > RESUME_MAX_CANDIDATES) limiter.mark(`${field}.worktrees`);
      if ((candidate.conflicts || []).length > RESUME_MAX_CANDIDATES) limiter.mark(`${field}.conflicts`);
      if ((candidate.metadata_errors || []).length > RESUME_MAX_CANDIDATES) {
        limiter.mark(`${field}.metadata_errors`);
      }
      return {
        id: candidate.id,
        slug: limiter.text(candidate.slug, RESUME_TEXT_LIMITS.short, `${field}.slug`),
        state: candidate.status,
        docs_path: limiter.text(candidate.dev_docs_path, RESUME_TEXT_LIMITS.path, `${field}.docs_path`),
        worktree_path: limiter.text(candidate.worktree_path, RESUME_TEXT_LIMITS.path, `${field}.worktree_path`),
        worktrees: (candidate.worktrees || [])
          .slice(0, RESUME_MAX_CANDIDATES)
          .map((worktree, worktreeIndex) => boundedWorktree(worktree, `${field}.worktrees[${worktreeIndex}]`)),
        conflicts: (candidate.conflicts || []).slice(0, RESUME_MAX_CANDIDATES).map((conflict, conflictIndex) => {
          const conflictField = `${field}.conflicts[${conflictIndex}]`;
          if ((conflict.values || []).length > RESUME_MAX_CANDIDATES) limiter.mark(`${conflictField}.values`);
          return {
            field: limiter.text(conflict.field, RESUME_TEXT_LIMITS.short, `${conflictField}.field`),
            values: (conflict.values || []).slice(0, RESUME_MAX_CANDIDATES).map((entry, valueIndex) => {
              const valueField = `${conflictField}.values[${valueIndex}]`;
              if ((entry.worktrees || []).length > RESUME_MAX_CANDIDATES) {
                limiter.mark(`${valueField}.worktrees`);
              }
              return {
                value: boundedValue(entry.value, `${valueField}.value`),
                worktrees: (entry.worktrees || [])
                  .slice(0, RESUME_MAX_CANDIDATES)
                  .map((worktree, worktreeIndex) => boundedWorktree(
                    worktree,
                    `${valueField}.worktrees[${worktreeIndex}]`
                  )),
              };
            }),
          };
        }),
        metadata_errors: (candidate.metadata_errors || [])
          .slice(0, RESUME_MAX_CANDIDATES)
          .map((entry, errorIndex) => {
            const errorField = `${field}.metadata_errors[${errorIndex}]`;
            if ((entry.errors || []).length > RESUME_MAX_CANDIDATES) {
              limiter.mark(`${errorField}.errors`);
            }
            return {
              ...boundedWorktree(entry, errorField),
              errors: (entry.errors || []).slice(0, RESUME_MAX_CANDIDATES).map((error, itemIndex) =>
                limiter.text(error, RESUME_TEXT_LIMITS.warning, `${errorField}.errors[${itemIndex}]`)
              ),
            };
          }),
      };
    }),
    truncated_fields: limiter.fields,
  };
  console.log(JSON.stringify({ version: 4, error }));
  return resumeFailureExitCode(result.reason);
}

function readResumeStatus(repoRoot, task) {
  const statusPath = resolveTaskStatusDoc(path.join(repoRoot, task.dev_docs_path));
  const statusRaw = readText(statusPath);
  const status = statusRaw
    ? getBundleStatusFromStatusDoc(statusRaw, path.basename(statusPath))
    : { status: null, error: 'Missing 01-status.md.' };
  return {
    path: toPosix(path.relative(repoRoot, statusPath)),
    state: status.status || task.status || 'unknown',
    goal: getMarkdownSectionText(statusRaw, 'Goal') || null,
    current_phase: getMarkdownListField(statusRaw, 'Progress', 'Current phase') || null,
    next_step: getMarkdownListField(statusRaw, 'Progress', 'Next step') || null,
    blocker: getMarkdownListField(statusRaw, 'Progress', 'Blocker') || null,
    acceptance_references: getMarkdownChecklistItems(statusRaw, 'Done when'),
    status_error: status.error || null,
  };
}

function readResumePitfalls(repoRoot, task) {
  const pitfallsPath = resolveTaskPitfallsDoc(path.join(repoRoot, task.dev_docs_path));
  const pitfallsRaw = readText(pitfallsPath);
  return {
    path: toPosix(path.relative(repoRoot, pitfallsPath)),
    present: pitfallsRaw !== null,
    items: getPitfallTableItems(pitfallsRaw, 5),
  };
}

function readResumeRoadmap(repoRoot, task) {
  const roadmapPath = resolveTaskRoadmapDoc(path.join(repoRoot, task.dev_docs_path));
  const kickoff = getRoadmapKickoff(readText(roadmapPath));
  return {
    path: toPosix(path.relative(repoRoot, roadmapPath)),
    kickoff_status: kickoff.status || 'unknown',
    kickoff_checked: kickoff.checked,
    kickoff_total: kickoff.total,
  };
}

function buildResumeSuggestions({ task, commits, worktree, pitfalls }) {
  const taskPath = String(task.dev_docs_path || '').replace(/\/+$/, '');
  const reads = [task.roadmap_path || `${taskPath}/00-roadmap.md`];
  if (pitfalls.present) reads.push(pitfalls.path);
  const commands = [];
  if (worktree && !worktree.clean) commands.push('git status --short', 'git diff');
  const latest = commits.at(-1);
  if (latest) commands.push(`git show --stat ${latest.sha}`);
  return { reads, commands };
}

export function cmdResume({ repoRoot, taskId, limit, scan, limitClamped, scanClamped }) {
  const branch = readCurrentBranch(repoRoot);
  const resolved = resolveResumeTaskContext({ repoRoot, taskId, branch });
  if (!resolved.ok) return { exitCode: renderResumeFailure(resolved) };

  const task = resolved.task;
  const statusDoc = readResumeStatus(repoRoot, task);
  const roadmap = readResumeRoadmap(repoRoot, task);
  const pitfalls = readResumePitfalls(repoRoot, task);
  const records = readCommitTimeline({ repoRoot, scan });
  if (records === null) {
    return {
      exitCode: renderResumeFailure({
        ok: false,
        reason: 'git-unavailable',
        branch,
        branchTaskIds: taskIdsFromBranch(branch),
        candidates: [],
      }),
    };
  }

  const linked = records.filter((record) => record.tasks.includes(task.id));
  const commits = linked.slice(0, limit).reverse().map(({ commit, sha, date, author, subject, phase, verify }) => ({
    commit, sha, date, author, subject, phase, verify,
  }));
  const worktree = readWorktreeStatus(repoRoot);
  const warnings = [];
  if (limitClamped) warnings.push(`Requested commit limit exceeded the maximum; using ${limit}.`);
  if (scanClamped) warnings.push(`Requested scan limit exceeded the maximum; using ${scan}.`);
  if (statusDoc.status_error) warnings.push(statusDoc.status_error);
  if (!statusDoc.goal) warnings.push(`Goal is missing from ${statusDoc.path}.`);
  if (!statusDoc.current_phase) warnings.push(`Current phase is missing from ${statusDoc.path}.`);
  if (!statusDoc.next_step) warnings.push(`Next step is missing from ${statusDoc.path}.`);
  if (!statusDoc.blocker) warnings.push(`Blocker is missing from ${statusDoc.path}.`);
  if (statusDoc.acceptance_references.length === 0) {
    warnings.push(`Done when has no acceptance references in ${statusDoc.path}.`);
  }
  if (roadmap.kickoff_status === 'unknown') warnings.push(`Kickoff status is missing or invalid in ${roadmap.path}.`);
  if (linked.length === 0) warnings.push(`No commit carries "Task: ${task.id}"; linked progress is unknown, not zero.`);
  if (records.length >= scan) warnings.push(`Commit scan limit reached (${scan}); older commits were not examined.`);
  if (worktree === null) warnings.push('Worktree state is unavailable.');
  else if (!worktree.clean) warnings.push(`${worktree.count} repo-wide uncommitted change(s) may be ahead of the linked commit timeline.`);

  const suggestions = buildResumeSuggestions({ task, commits, worktree, pitfalls });
  const limiter = createResumeTextLimiter();
  const boundedCommits = commits.map((commit, index) => ({
    commit: commit.commit,
    sha: commit.sha,
    date: limiter.text(commit.date, RESUME_TEXT_LIMITS.short, `timeline.commits[${index}].date`),
    author: limiter.text(commit.author, RESUME_TEXT_LIMITS.short, `timeline.commits[${index}].author`),
    subject: limiter.text(commit.subject, RESUME_TEXT_LIMITS.commitSubject, `timeline.commits[${index}].subject`),
    phase: limiter.text(commit.phase, RESUME_TEXT_LIMITS.commitMetadata, `timeline.commits[${index}].phase`),
    verify: limiter.text(commit.verify, RESUME_TEXT_LIMITS.commitMetadata, `timeline.commits[${index}].verify`),
  }));
  const boundedWorktree = worktree === null ? null : {
    ...worktree,
    entries: worktree.entries.map((entry, index) =>
      limiter.text(entry, RESUME_TEXT_LIMITS.path, `worktree.entries[${index}]`)
    ),
  };
  if (statusDoc.acceptance_references.length > RESUME_MAX_ACCEPTANCE_REFERENCES) {
    limiter.mark('status.acceptance_references');
  }
  const packet = {
    version: 4,
    task: {
      id: task.id,
      slug: limiter.text(task.slug, RESUME_TEXT_LIMITS.short, 'task.slug'),
      state: statusDoc.state,
      docs_path: limiter.text(docsTrailerValue(task.dev_docs_path), RESUME_TEXT_LIMITS.path, 'task.docs_path'),
      resolution: resolved.source,
    },
    status: {
      path: limiter.text(statusDoc.path, RESUME_TEXT_LIMITS.path, 'status.path'),
      goal: limiter.text(statusDoc.goal, RESUME_TEXT_LIMITS.text, 'status.goal'),
      current_phase: limiter.text(
        statusDoc.current_phase,
        RESUME_TEXT_LIMITS.text,
        'status.current_phase'
      ),
      next_step: limiter.text(statusDoc.next_step, RESUME_TEXT_LIMITS.text, 'status.next_step'),
      blocker: limiter.text(statusDoc.blocker, RESUME_TEXT_LIMITS.text, 'status.blocker'),
      acceptance_references: statusDoc.acceptance_references
        .slice(0, RESUME_MAX_ACCEPTANCE_REFERENCES)
        .map((item, index) => ({
          checked: item.checked,
          reference: limiter.text(
            item.text,
            RESUME_TEXT_LIMITS.text,
            `status.acceptance_references[${index}].reference`
          ),
        })),
    },
    roadmap: {
      path: limiter.text(roadmap.path, RESUME_TEXT_LIMITS.path, 'roadmap.path'),
      kickoff_status: roadmap.kickoff_status,
      kickoff_checked: roadmap.kickoff_checked,
      kickoff_total: roadmap.kickoff_total,
    },
    repository: {
      branch: limiter.text(branch, RESUME_TEXT_LIMITS.short, 'repository.branch'),
      head: readHeadCommit(repoRoot),
    },
    timeline: {
      state: linked.length > 0 ? 'linked' : 'unknown',
      linked_total: linked.length,
      scanned_commits: records.length,
      scan_limit: scan,
      limit,
      commits: boundedCommits,
    },
    worktree: boundedWorktree,
    do_not_repeat: pitfalls.items.map((item, index) =>
      limiter.text(item, RESUME_TEXT_LIMITS.text, `do_not_repeat[${index}]`)
    ),
    warnings: warnings.map((warning, index) =>
      limiter.text(warning, RESUME_TEXT_LIMITS.warning, `warnings[${index}]`)
    ),
    suggested_reads: suggestions.reads.map((value, index) =>
      limiter.text(value, RESUME_TEXT_LIMITS.path, `suggested_reads[${index}]`)
    ),
    suggested_commands: suggestions.commands.map((value, index) =>
      limiter.text(value, RESUME_TEXT_LIMITS.path, `suggested_commands[${index}]`)
    ),
  };
  packet.truncated_fields = [...limiter.fields];
  console.log(JSON.stringify(packet));
  return { exitCode: 0, packet };
}
