/**
 * Read-only validation for the project-governance system.
 */

import fs from 'node:fs';
import path from 'node:path';

import {
  FEATURE_ID_RE,
  FEATURE_STATUS,
  MILESTONE_ID_RE,
  MILESTONE_STATUS,
  TASK_ID_RE,
  TASK_STATUS,
  cleanMarkdownValue,
  exists,
  formatTaskRef,
  getBundleStatusFromStatusDoc,
  getAutoGeneratedContent,
  getMarkdownChecklistItems,
  getMarkdownSectionLines,
  getRoadmapKickoff,
  loadRegistry,
  normalizeEol,
  parseTaskMeta,
  readText,
  renderDashboardProjection,
  renderFeatureMap,
  scanTasks,
  toPosix,
} from './governance-read.mjs';

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

function validateExactFields(value, label, fields, errors) {
  const allowed = new Set(fields);
  for (const field of fields) {
    if (!Object.hasOwn(value, field) || value[field] === undefined) {
      errors.push(`${label} is missing required field "${field}".`);
    }
  }
  for (const field of Object.keys(value)) {
    if (!allowed.has(field)) errors.push(`${label} contains unsupported field "${field}".`);
  }
}

function validateStringField(value, label, field, errors, { allowEmpty = false } = {}) {
  if (typeof value[field] !== 'string' || (!allowEmpty && !value[field].trim())) {
    errors.push(`${label} field "${field}" must be ${allowEmpty ? 'a string' : 'a non-empty string'}.`);
  } else if (value[field] !== value[field].trim()) {
    errors.push(`${label} field "${field}" must not have leading or trailing whitespace.`);
  }
}

const TASK_TEMPLATE_DOCUMENTS = [
  '00-roadmap.md',
  '01-status.md',
  '02-architecture.md',
  'verification.md',
  'requirement.md',
  'implementation.md',
  'pitfalls.md',
];

function validateAuthoringComments(task) {
  const errors = [];
  for (const name of TASK_TEMPLATE_DOCUMENTS) {
    const raw = readText(path.join(task.absPath, name));
    if (raw !== null && /<!--[\s\S]*?-->/.test(raw)) {
      errors.push(`${name} contains an authoring comment from a task template.`);
    }
  }
  return errors;
}

function validateRoadmap(roadmapRaw) {
  const raw = normalizeEol(roadmapRaw);
  const errors = [];
  const requiredHeadings = [
    'scope and constraints',
    'decision alignment',
    'task relationships',
    'implementation plan',
    'kickoff gate',
    'risks and recovery',
    'phase closeout',
  ];
  const headings = new Set();

  for (const line of raw.split('\n')) {
    const match = line.trim().match(/^##\s+(.+?)\s*$/);
    if (match) headings.add(String(match[1] || '').trim().toLowerCase());
  }

  const missingHeadings = requiredHeadings.filter((heading) => !headings.has(heading));
  if (missingHeadings.length > 0) {
    errors.push(`Roadmap is missing required sections: ${missingHeadings.join(', ')}.`);
  }

  if (/\bproposed:[a-z0-9][a-z0-9-]*\b/i.test(raw)) {
    errors.push('Roadmap contains an unsupported proposed:<slug> relationship; open a task or use the project Idea list.');
  }

  const kickoff = getRoadmapKickoff(raw);
  if (!kickoff.status) {
    errors.push('Kickoff gate must contain "- Status: pending" or "- Status: ready".');
  }

  // The gate's contract is its four dimensions, not any four checkboxes. Each item carries a
  // stable, visible category prefix; the wording after the colon stays open to the task. This is
  // a structural check only — it does not certify the quality of what an item claims.
  const gateCategories = ['Decisions', 'Design', 'Route', 'Verification'];
  const seenCategories = new Map();
  const unclassifiedItems = [];
  for (const item of getMarkdownChecklistItems(raw, 'Kickoff gate')) {
    const match = item.text.match(/^(Decisions|Design|Route|Verification):\s*(.+)$/);
    if (!match) {
      unclassifiedItems.push(item.text);
      continue;
    }
    seenCategories.set(match[1], (seenCategories.get(match[1]) || 0) + 1);
  }
  const missingCategories = gateCategories.filter((category) => !seenCategories.has(category));
  const duplicateCategories = gateCategories.filter(
    (category) => (seenCategories.get(category) || 0) > 1
  );
  for (const text of unclassifiedItems) {
    errors.push(
      `Kickoff gate item must start with one of ${gateCategories
        .map((category) => `"${category}:"`)
        .join(', ')}: "${text}".`
    );
  }
  if (missingCategories.length > 0) {
    errors.push(`Kickoff gate is missing required categories: ${missingCategories.join(', ')}.`);
  }
  if (duplicateCategories.length > 0) {
    errors.push(`Kickoff gate has duplicate categories: ${duplicateCategories.join(', ')}.`);
  }
  const gateStructureValid =
    unclassifiedItems.length === 0 && missingCategories.length === 0 && duplicateCategories.length === 0;
  if (gateStructureValid && kickoff.status === 'ready' && kickoff.checked !== kickoff.total) {
    errors.push(`Kickoff is ready but only ${kickoff.checked}/${kickoff.total} gate items are checked.`);
  } else if (gateStructureValid && kickoff.status === 'pending' && kickoff.checked === kickoff.total) {
    errors.push('Kickoff is pending even though every gate item is checked.');
  }

  const implementationPlan = getMarkdownSectionLines(raw, 'Implementation plan').join('\n');
  const phaseMatches = [
    ...implementationPlan.matchAll(/^###\s+Phase\s+\d+\s+[—–-]\s+.+$/gim),
  ];
  if (phaseMatches.length === 0) {
    errors.push(
      'Implementation plan must contain at least one named phase heading like "### Phase 1 — <name>".'
    );
    return errors;
  }

  for (let index = 0; index < phaseMatches.length; index++) {
    const start = phaseMatches[index].index;
    const end = phaseMatches[index + 1]?.index ?? implementationPlan.length;
    const phaseRaw = implementationPlan.slice(start, end);
    const phaseName = String(phaseMatches[index][0] || `Phase ${index + 1}`).trim();

    const outcome = phaseRaw.match(/^\s*-\s+Outcome:\s*(.+)$/mi);
    if (!outcome || !cleanMarkdownValue(outcome[1])) {
      errors.push(`${phaseName} is missing a populated "Outcome" field.`);
    }

    if (index > 0) continue;
    const plannedMatch = phaseRaw.match(/^\s*-\s+Planned changes:\s*$/im);
    if (!plannedMatch) {
      errors.push('The first roadmap phase is missing "Planned changes".');
    } else {
      // Only the list block directly under "Planned changes" counts, not numbered lines that
      // happen to appear inside other phase fields.
      const afterHeading = phaseRaw.slice(plannedMatch.index + plannedMatch[0].length);
      const nextField = afterHeading.search(/^\s*-\s+\S/m);
      const plannedBlock = nextField === -1 ? afterHeading : afterHeading.slice(0, nextField);
      if (!/^\s*\d+\.\s+\S.+$/m.test(plannedBlock)) {
        errors.push('The first roadmap phase needs at least one ordered planned change.');
      }
    }
  }

  return errors;
}

function collectRegistryIds(registry, key, label, idPattern, errors) {
  const items = registry[key];
  const ids = new Map();
  if (!Array.isArray(items)) {
    errors.push(`Registry "${key}" must be a list.`);
    return ids;
  }

  for (const item of items) {
    if (!item || typeof item !== 'object' || Array.isArray(item)) {
      errors.push(`${label} entry must be a mapping.`);
      continue;
    }
    const rawId = item.id;
    if (typeof rawId !== 'string' || !rawId) {
      errors.push(`${label} is missing required "id" field.`);
      continue;
    }
    const id = rawId;
    if (id !== id.trim()) {
      errors.push(`${label} ID "${id}" must not have leading or trailing whitespace.`);
      continue;
    }
    if (!idPattern.test(id)) {
      errors.push(`${label} ID "${id}" does not match the required format.`);
      continue;
    }
    if (ids.has(id)) {
      errors.push(`Duplicate ${label} ID "${id}" in registry.`);
      continue;
    }
    ids.set(id, item);
  }
  return ids;
}

function validateRegistryGraph(registry, errors, { validateTasks = true } = {}) {
  if (registry.version !== 1) {
    errors.push('Registry version must be 1.');
  }

  const milestones = collectRegistryIds(
    registry,
    'milestones',
    'Milestone',
    MILESTONE_ID_RE,
    errors
  );
  const features = collectRegistryIds(registry, 'features', 'Feature', FEATURE_ID_RE, errors);
  const tasks = collectRegistryIds(registry, 'tasks', 'Task', TASK_ID_RE, errors);
  if (registry.ideas !== undefined && !Array.isArray(registry.ideas)) {
    errors.push('Registry "ideas" must be a list when present.');
  } else {
    for (const [index, idea] of (registry.ideas || []).entries()) {
      if (!idea || typeof idea !== 'object' || Array.isArray(idea)) {
        errors.push(`Registry Idea at index ${index} must be a mapping with only a non-empty "idea" field.`);
        continue;
      }
      const keys = Object.keys(idea);
      if (
        keys.length !== 1 ||
        keys[0] !== 'idea' ||
        typeof idea.idea !== 'string' ||
        !idea.idea.trim() ||
        idea.idea !== idea.idea.trim()
      ) {
        errors.push(`Registry Idea at index ${index} must contain only a non-empty "idea" field.`);
      }
    }
  }

  if (!milestones.has('M-000')) errors.push('Registry is missing reserved Milestone M-000.');
  if (!features.has('F-000')) errors.push('Registry is missing reserved Feature F-000.');
  if (features.has('F-000') && String(features.get('F-000').milestone_id || '') !== 'M-000') {
    errors.push('Reserved Feature F-000 must belong to Milestone M-000.');
  }

  for (const [id, milestone] of milestones) {
    const label = `Milestone ${id}`;
    validateExactFields(milestone, label, ['id', 'title', 'status', 'description'], errors);
    validateStringField(milestone, label, 'title', errors);
    validateStringField(milestone, label, 'description', errors, { allowEmpty: true });
  }

  for (const [id, feature] of features) {
    const label = `Feature ${id}`;
    validateExactFields(
      feature,
      label,
      ['id', 'title', 'milestone_id', 'status', 'description'],
      errors
    );
    validateStringField(feature, label, 'title', errors);
    validateStringField(feature, label, 'description', errors, { allowEmpty: true });
    const rawMilestoneId = feature.milestone_id;
    const milestoneId = typeof rawMilestoneId === 'string' ? rawMilestoneId : '';
    if (!milestoneId) errors.push(`Feature ${id} is missing milestone_id.`);
    else if (milestoneId !== milestoneId.trim()) {
      errors.push(`Feature ${id} milestone_id must not have leading or trailing whitespace.`);
    } else if (!milestones.has(milestoneId)) {
      errors.push(`Feature ${id} references missing Milestone ${milestoneId}.`);
    }
  }

  for (const [id, task] of tasks) {
    const label = `Task ${id}`;
    if (validateTasks) {
      validateExactFields(
        task,
        label,
        ['id', 'slug', 'status', 'updated', 'dev_docs_path', 'feature_id'],
        errors
      );
      validateStringField(task, label, 'slug', errors);
      validateStringField(task, label, 'dev_docs_path', errors);
      if (typeof task.updated !== 'string' || !DATE_RE.test(task.updated)) {
        errors.push(`Task ${id} field "updated" must use YYYY-MM-DD.`);
      }
    }
    const rawFeatureId = task.feature_id;
    const featureId = typeof rawFeatureId === 'string' ? rawFeatureId : '';
    if (!featureId) errors.push(`Task ${id} is missing feature_id.`);
    else if (featureId !== featureId.trim()) {
      errors.push(`Task ${id} feature_id must not have leading or trailing whitespace.`);
    } else if (!features.has(featureId)) {
      errors.push(`Task ${id} references missing Feature ${featureId}.`);
    }
  }
}

function validateRegistryStatuses(items, label, allowed, errors, projection = false) {
  if (!Array.isArray(items)) return;
  const field = projection ? 'registry status' : 'status';
  for (const item of items) {
    if (!item || typeof item !== 'object') continue;
    const id = typeof item.id === 'string' ? item.id : '';
    const status = typeof item.status === 'string' ? item.status : '';
    if (!status) errors.push(`${label} ${id}: Missing ${field}.`);
    else if (status !== status.trim()) {
      errors.push(`${label} ${id}: ${field} must not have leading or trailing whitespace.`);
    } else if (!allowed.has(status)) {
      errors.push(`${label} ${id}: Invalid ${field} "${status}". Allowed: ${[...allowed].join(', ')}`);
    }
  }
}

export function getRegistryDataErrors(
  registry,
  { validateTasks = true } = {}
) {
  if (!registry || typeof registry !== 'object' || Array.isArray(registry)) {
    return ['Registry root must be a mapping.'];
  }
  const errors = [];
  const requiredKeys = ['version', 'milestones', 'features', 'ideas', 'tasks'];
  validateExactFields(registry, 'Registry', requiredKeys, errors);
  validateRegistryGraph(registry, errors, { validateTasks });
  validateRegistryStatuses(registry.milestones, 'Milestone', MILESTONE_STATUS, errors);
  validateRegistryStatuses(registry.features, 'Feature', FEATURE_STATUS, errors);
  if (validateTasks) validateRegistryStatuses(registry.tasks, 'Task', TASK_STATUS, errors, true);

  const features = Array.isArray(registry.features) ? registry.features : [];
  const tasks = Array.isArray(registry.tasks) ? registry.tasks : [];
  for (const milestone of Array.isArray(registry.milestones) ? registry.milestones : []) {
    if (!milestone || typeof milestone !== 'object' || milestone.status !== 'done') continue;
    const milestoneId = String(milestone.id || '');
    const incomplete = features
      .filter((feature) => feature && String(feature.milestone_id || '') === milestoneId)
      .filter((feature) => !['done', 'cut'].includes(String(feature.status || '')))
      .map((feature) => String(feature.id || '(missing ID)'));
    if (incomplete.length > 0) {
      errors.push(
        `Milestone ${milestoneId} is done but has non-terminal Features: ${incomplete.join(', ')}.`
      );
    }
  }

  if (!validateTasks) return errors;
  for (const feature of features) {
    if (!feature || typeof feature !== 'object' || !['done', 'cut'].includes(feature.status)) continue;
    const featureId = String(feature.id || '');
    const activeTasks = tasks
      .filter((task) => task && String(task.feature_id || '') === featureId)
      .filter((task) => ['planned', 'in-progress', 'blocked'].includes(String(task.status || '')))
      .map((task) => String(task.id || '(missing ID)'));
    if (activeTasks.length > 0) {
      errors.push(
        `Feature ${featureId} is ${feature.status} but has non-terminal mapped Tasks: ${activeTasks.join(', ')}.`
      );
    }
  }
  return errors;
}

export function cmdLint({ repoRoot, strict, taskId = null }) {
  const errors = [];
  const warnings = [];
  const scoped = taskId !== null;
  if (scoped && !TASK_ID_RE.test(String(taskId || ''))) {
    errors.push(`Invalid --task (expected T-###, got "${taskId || ''}").`);
  }

  for (const file of ['AGENTS.md', 'CLAUDE.md']) {
    const guidancePath = path.join(repoRoot, '.ai', 'project', file);
    if (!exists(guidancePath)) errors.push(`Missing .ai/project/${file} (required).`);
  }
  const projectClaudeEntry = readText(path.join(repoRoot, '.ai', 'project', 'CLAUDE.md'));
  const expectedProjectClaudeEntry = '# Project governance\n\nFollow `AGENTS.md` for this directory.';
  if (projectClaudeEntry !== null && normalizeEol(projectClaudeEntry).trim() !== expectedProjectClaudeEntry) {
    errors.push('.ai/project/CLAUDE.md must contain only the project-governance pointer to AGENTS.md.');
  }
  const dashboardRaw = readText(path.join(repoRoot, '.ai', 'project', 'dashboard.md'));
  if (dashboardRaw === null) {
    errors.push('Missing .ai/project/dashboard.md (required derived view).');
  } else if (
    !dashboardRaw.includes('<!-- AUTO-GENERATED:START dashboard -->') ||
    !dashboardRaw.includes('<!-- AUTO-GENERATED:END dashboard -->')
  ) {
    errors.push('dashboard.md is missing its required AUTO-GENERATED markers.');
  }
  const featureMapRaw = readText(path.join(repoRoot, '.ai', 'project', 'feature-map.md'));
  const featureMapStart = '# Feature Map\n\n<!-- AUTO-GENERATED:START feature-map -->';
  const featureMapEnd = '<!-- AUTO-GENERATED:END feature-map -->';
  if (featureMapRaw === null) {
    errors.push('Missing .ai/project/feature-map.md (required derived view).');
  } else {
    const normalizedFeatureMap = normalizeEol(featureMapRaw).trim();
    if (!normalizedFeatureMap.startsWith(featureMapStart) || !normalizedFeatureMap.endsWith(featureMapEnd)) {
      errors.push('feature-map.md must contain only its generated Feature map and required markers.');
    }
  }

  const { registry, error: registryParseError } = loadRegistry(repoRoot);

  if (registryParseError) {
    errors.push(`Failed to parse registry.json: ${registryParseError}`);
  }

  if (!registry && !registryParseError) {
    warnings.push(
      'Project hub is not initialized. Run the repository task-system installer from its skill source.'
    );
  } else if (registry) {
    const registryErrors = getRegistryDataErrors(registry);
    errors.push(...registryErrors);
    if (registryErrors.length === 0) {
      if (
        dashboardRaw !== null &&
        getAutoGeneratedContent(dashboardRaw, 'dashboard') !==
          renderDashboardProjection(registry).trim()
      ) {
        errors.push('dashboard.md generated content is stale relative to registry.json.');
      }
      if (
        featureMapRaw !== null &&
        normalizeEol(featureMapRaw).trimEnd() !== normalizeEol(renderFeatureMap(registry)).trimEnd()
      ) {
        errors.push('feature-map.md generated content is stale relative to registry.json.');
      }
    }
  }

  const taskDocsDir = path.join(repoRoot, 'dev-docs');
  for (const directory of ['active', 'archive']) {
    if (!exists(path.join(taskDocsDir, directory))) {
      errors.push(`Required task-document directory dev-docs/${directory}/ is missing.`);
    }
  }
  for (const file of ['AGENTS.md', 'CLAUDE.md']) {
    if (!exists(path.join(taskDocsDir, file))) {
      errors.push(`Required task-document entry point dev-docs/${file} is missing.`);
    }
  }
  const claudeEntry = readText(path.join(taskDocsDir, 'CLAUDE.md'));
  const expectedClaudeEntry = '# Task documentation\n\nFollow `AGENTS.md` for task-document semantics.';
  if (claudeEntry !== null && normalizeEol(claudeEntry).trim() !== expectedClaudeEntry) {
    errors.push('dev-docs/CLAUDE.md must contain only the task-document pointer to AGENTS.md.');
  }

  const tasks = scanTasks(repoRoot);

  // Collect IDs and slug-to-ids mapping for duplicate checks.
  const taskIdToTask = new Map();
  const slugToIds = new Map();
  let scopedOccurrences = 0;

  const registryTaskById = new Map();
  if (registry && Array.isArray(registry.tasks)) {
    for (const t of registry.tasks) {
      if (!t || typeof t !== 'object') continue;
      const id = typeof t.id === 'string' ? t.id : '';
      if (id) registryTaskById.set(id, t);
    }
  }

  for (const task of tasks) {
    const metaRaw = readText(task.metaPath);

    task.taskId = null;
    task.bundleStatus = null;
    task.effectiveStatus = task.phase === 'archive' ? 'archived' : null;

    let meta = null;
    let taskInScope = !scoped;
    if (metaRaw === null) {
      if (!scoped) errors.push(`${formatTaskRef(task)}: Missing .ai-task.json.`);
    } else {
      const parsed = parseTaskMeta(metaRaw);
      if (parsed.parse_error) {
        if (!scoped) {
          errors.push(`${formatTaskRef(task)}: Failed to parse .ai-task.json: ${parsed.parse_error}`);
        }
      } else {
        meta = parsed;
        if (TASK_ID_RE.test(meta.task_id)) {
          task.taskId = meta.task_id;
          taskInScope = !scoped || meta.task_id === taskId;
          if (taskInScope && scoped) scopedOccurrences++;
          if (taskIdToTask.has(meta.task_id)) {
            const other = taskIdToTask.get(meta.task_id);
            if (!scoped || meta.task_id === taskId) {
              errors.push(
                `Duplicate task_id "${meta.task_id}" across repo:\n  - ${toPosix(other.relPath)}\n  - ${toPosix(task.relPath)}`
              );
            }
          } else {
            taskIdToTask.set(meta.task_id, task);
          }

          const ids = slugToIds.get(task.slug) || new Set();
          ids.add(meta.task_id);
          slugToIds.set(task.slug, ids);
        }

        for (const schemaError of meta.schema_errors) {
          if (taskInScope) {
            errors.push(`${formatTaskRef(task)}: Invalid .ai-task.json: ${schemaError}`);
          }
        }
      }
    }

    if (!taskInScope) continue;

    const statusRaw = readText(task.statusPath);
    const roadmapRaw = readText(task.roadmapPath);
    const kickoff = roadmapRaw ? getRoadmapKickoff(roadmapRaw) : null;

    if (task.phase === 'archive') {
      const names = fs.readdirSync(task.absPath).sort();
      const hasSummary = names.includes('summary.md');
      const hasMeta = names.includes('.ai-task.json');
      const allowed = new Set(['.ai-task.json', 'summary.md']);
      const extras = names.filter((name) => !allowed.has(name));
      if (!hasSummary || !hasMeta || extras.length > 0 || names.length !== 2) {
        const details = [];
        if (!hasMeta) details.push('missing .ai-task.json');
        if (!hasSummary) details.push('missing summary.md');
        if (extras.length > 0) details.push(`extra entries: ${extras.join(', ')}`);
        errors.push(
          `${formatTaskRef(task)}: Archived bundle must contain exactly .ai-task.json and summary.md` +
            `${details.length > 0 ? `; ${details.join('; ')}` : ''}.`
        );
      }
    }

    if (task.phase === 'active') {
      const requiredFiles = [
        '00-roadmap.md',
        '01-status.md',
        '02-architecture.md',
        'verification.md',
      ];
      const missingFiles = requiredFiles.filter((name) => !exists(path.join(task.absPath, name)));
      if (missingFiles.length > 0) {
        errors.push(
          `${formatTaskRef(task)}: Active bundle is incomplete; missing: ${missingFiles.join(', ')}.`
        );
      }

      if (roadmapRaw !== null) {
        for (const roadmapError of validateRoadmap(roadmapRaw)) {
          errors.push(`${formatTaskRef(task)}: ${roadmapError}`);
        }
      }
      for (const commentError of validateAuthoringComments(task)) {
        errors.push(`${formatTaskRef(task)}: ${commentError}`);
      }
    }

    if (task.phase === 'active' && statusRaw !== null) {
      const { status, error: stateError } = getBundleStatusFromStatusDoc(
        statusRaw,
        path.basename(task.statusPath)
      );
      if (stateError) errors.push(`${formatTaskRef(task)}: ${stateError}`);
      task.bundleStatus = status;
      if (status) task.effectiveStatus = status;
    }

    if (task.phase === 'active' && task.effectiveStatus === 'done' && kickoff?.status !== 'ready') {
      errors.push(`${formatTaskRef(task)}: State is done but roadmap kickoff is not ready.`);
    }

    if (!meta || !TASK_ID_RE.test(meta.task_id)) continue;

    if (meta.slug !== task.slug) {
      errors.push(`${formatTaskRef(task)}: meta.slug="${meta.slug}" does not match directory slug "${task.slug}".`);
    }

    // Registry consistency checks (strict for tasks with meta)
    if (registry) {
      if (!registryTaskById.has(meta.task_id)) {
        errors.push(`${formatTaskRef(task)}: Missing registry entry for task_id "${meta.task_id}".`);
      } else {
        const entry = registryTaskById.get(meta.task_id);
        const expectedPath = toPosix(task.relPath);
        const actualPath = toPosix(String(entry.dev_docs_path || ''));
        if (actualPath !== expectedPath) {
          errors.push(
            `${formatTaskRef(task)}: registry dev_docs_path mismatch (registry="${actualPath}", expected="${expectedPath}").`
          );
        }
        const expectedStatus = task.effectiveStatus;
        const actualStatus = String(entry.status || '');
        if (expectedStatus && actualStatus && expectedStatus !== actualStatus) {
          errors.push(
            `${formatTaskRef(task)}: registry status mismatch (registry="${actualStatus}", expected="${expectedStatus}").`
          );
        }
      }
    }
  }

  if (scoped && scopedOccurrences === 0) {
    errors.push(
      `Task "${taskId}" has no valid bundle in this worktree. Repair its identity before scoped lint.`
    );
  }

  // A slug linked to multiple distinct IDs is ambiguous.
  for (const [slug, ids] of slugToIds.entries()) {
    if (ids.size <= 1) continue;
    if (scoped && !ids.has(taskId)) continue;
    errors.push(`Slug "${slug}" appears with multiple task_ids: ${[...ids].sort().join(', ')}`);
  }

  // Orphaned registry entries (task deleted from filesystem but still in registry)
  if (!scoped && registry && Array.isArray(registry.tasks)) {
    for (const regTask of registry.tasks) {
      if (!regTask || typeof regTask !== 'object') continue;
      const id = typeof regTask.id === 'string' ? regTask.id : '';
      if (!id) continue;
      // Skip tasks that were found on disk
      if (taskIdToTask.has(id)) continue;
      const devDocsPath = String(regTask.dev_docs_path || '');
      if (!/^dev-docs\/(?:active|archive)\/[^/]+$/.test(toPosix(devDocsPath))) {
        errors.push(
          `Registry task ${id} has unsupported dev_docs_path "${devDocsPath}"; task bundles must be immediate children of top-level dev-docs/active or dev-docs/archive.`
        );
        continue;
      }
      warnings.push(
        `Registry task ${id} (slug="${regTask.slug || ''}"): dev_docs_path "${devDocsPath}" not found on disk. ` +
          'Re-create the bundle, or remove the entry with "sync --prune --apply" after confirming it is gone from every linked worktree.'
      );
    }
  }

  if (strict && warnings.length > 0) {
    for (const warning of warnings) errors.push(`[strict] ${warning}`);
  }

  if (errors.length > 0) {
    console.log('Errors:');
    for (const e of errors) console.log(`- ${e}`);
  }

  if (warnings.length > 0) {
    console.log('Warnings:');
    for (const w of warnings) console.log(`- ${w}`);
  }

  const okExit = errors.length === 0;
  console.log(okExit ? '[ok] Lint passed.' : '[error] Lint failed.');
  return { ok: okExit, errors, warnings };
}
